name: macOS-Linux-GCC
on: [push, pull_request]

jobs:
  mac-linux-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [gfortran-10, gfortran-12]
        os: [ubuntu-latest, macos-latest]
        openmp: [ON, OFF]

    steps:
    
    - name: checkout-sp
      uses: actions/checkout@v2
      with: 
        path: sp

    - name: build-sp
      run: |
        cd sp
        mkdir build 
        cd build
        cmake .. -DOPENMP=${{ matrix.openmp }}
        make -j2

    - name: test-sp
      run: |
        cd sp/build
        ctest --output-on-failure

